config/routes.rb
Rails.application.routes.draw do

  resources 'shortener/shortened_urls',
    as: 'shortener_shortened_urls',
    controller: 'urls',
    path: 'urls' do
    member do
      get 'expand'
    end
  end

  get '/fitter_happier' => 'fitter_happier#index'
  get '/fitter_happier/site_check' => 'fitter_happier#site_check'
  get '/fitter_happier/site_and_database_check' => 'fitter_happier#site_and_database_check'

  get '/search' => "urls#search"

  get '/:id' => "urls#expand"
  get 'api/update.:format' => 'new_url#api_update'
  post 'new_url/create.:format' => 'new_url#create'

  root 'urls#index'

end

app/controllers/urls_controller.rb
require 'url_validator'

class UrlsController < ApplicationController
  http_basic_authenticate_with name: Setting.value('name'), password: Setting.value('password'),
                                except: :expand
  skip_before_action :verify_authenticity_token
  before_action :set_url, only: [:show, :edit, :update]
  
  include ApplicationHelper
  include NewUrlHelper

  def index
    @urls = Shortener::ShortenedUrl.where(domain_name: request.server_name.downcase).
              order(created_at: :desc).page(params[:page])
  end

  def new
    @url = Shortener::ShortenedUrl.new(domain_name: request.server_name.downcase)
  end

  def edit
  end

  def create
    
    urls = create_shortenURL(params['url'], params['unique_key'])
    
    @url = urls[:short_url]
    url = urls[:url]

    # This logic all really belongs in the Shortener::ShortenedUrl model.  This
    # ugliness seems to be a sign that we should fork that gem and extend it.
    if url.works?
      unless params['unique_key'].blank?
        if params['unique_key'] =~ /\A[a-zA-Z0-9]+\Z/
          if Shortener::ShortenedUrl.where(domain_name: request.server_name.downcase).
            where("lower(unique_key) = ?", params['unique_key'].downcase).exists?

            @url = Shortener::ShortenedUrl.new url: params['url'], domain_name: request.server_name.downcase
            @url.errors[:base] << 'That short code already exists.'
          else
            @url = Shortener::ShortenedUrl.generate(url.to_s)
            @url.unique_key = params['unique_key']
            @url.domain_name = request.server_name.downcase
            @url.save
          end
        else
          @url = Shortener::ShortenedUrl.new url: params['url'], domain_name: request.server_name.downcase
          @url.errors[:base] << 'Short codes can only include numbers and letters.'
        end
      else
        @url = Shortener::ShortenedUrl.generate(url.to_s)
        @url.domain_name = request.server_name.downcase
      end
    else
      @url = Shortener::ShortenedUrl.new url: params['url'], domain_name: request.server_name.downcase
      @url.errors[:base] << 'That URL doesn\'t seem to work.'
    end

    respond_to do |format|
      if url.works? and @url.errors.messages.empty?
        format.html { redirect_to @url }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Short URL was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  # find the real link for the shortened link key and redirect
  def expand
    # only use the leading valid characters
    token = /^([#{Shortener.key_chars.join}]*).*/i.match(params[:id])[1]

    # pull the link out of the db
    url = Shortener::ShortenedUrl.where(domain_name: request.server_name.downcase).
            where("lower(unique_key) = ?", token.downcase).first

    if url
      # don't want to wait for the increment to happen, make it snappy!
      # this is the place to enhance the metrics captured
      # for the system. You could log the request origin
      # browser type, ip address etc.
      Thread.new do
        url.increment!(:use_count)
        ActiveRecord::Base.connection.close
      end
      # do a 301 redirect to the destination url
      redirect_to full_url(url), :status => :moved_permanently
    else
      # if we don't find the shortened link, redirect to the root
      # make this configurable in future versions
      redirect_to '/'
    end
  end

  def search
    @urls = Shortener::ShortenedUrl.where('url LIKE ?', "%#{params[:q]}%").all.page(params[:page])

    return @urls
  end

  private

  def set_url
    @url = Shortener::ShortenedUrl.where(domain_name: request.server_name.downcase).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def url_params
    params.permit(
      :url,
      :unique_key,
      :utm_source, :utm_medium, :utm_term, :utm_content, :utm_name
    )
  end

end

app/views/urls/_form.html.haml
.panel-body
  - if @url.errors.any?
    #error_explanation
      %h2= "#{pluralize(@url.errors.count, "error")} prohibited this url from being saved:"
      %ul
        - @url.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    %label.col-sm-2.control-label{for: "url"} URL
    .col-sm-10
      = f.text_field :url, class: 'form-control', name: "url", placeholder: "http://...", type: "text"

  .form-group
    %label.col-sm-2.control-label{for: "unique_key"} Short Code
    .col-sm-10
      = f.text_field :unique_key, class: 'form-control', name: "unique_key", placeholder: "(optional, case insensitive) tiestopromo, nye2014, FREESTUFF", type: "text"

  .form-group
    %label.col-sm-2.control-label{for: "domain_names"} Domains
    .col-sm-10
      - @domains.each do |domain|
        = check_box_tag "domain_name[]", domain, @current_domain.nil? || @current_domain == domain, id: "domain_name_input_#{domain}"
        = label_tag :domain_name, domain, for: "domain_name_input_#{domain}"

  .panel.panel-default
    .panel-heading
      Google Analytics UTM parameters (optional)

    .panel-body
      - utm_help = 'https://support.google.com/analytics/answer/1033867'

      .form-group
        %label.col-sm-2.control-label{for: "utm_source"} Source
        .col-sm-10
          .input-group.input-group-sm
            = f.text_field :utm_source, class: 'form-control', name: 'utm_source', placeholder: 'referrer: google, citysearch, newsletter4', type: 'text'
            %span.input-group-addon
              %a{href: utm_help, target: 'utm_help'}
                %span.glyphicon.glyphicon-question-sign

      .form-group
        %label.col-sm-2.control-label{for: "utm_medium"} Medium
        .col-sm-10
          .input-group.input-group-sm
            = f.text_field :utm_medium, class: 'form-control', name: 'utm_medium', placeholder: 'marketing medium: cpc, banner, email', type: 'text'
            %span.input-group-addon
              %a{href: utm_help, target: 'utm_help'}
                %span.glyphicon.glyphicon-question-sign

      .form-group
        %label.col-sm-2.control-label{for: "utm_term"} Term
        .col-sm-10
          .input-group.input-group-sm
            = f.text_field :utm_term, class: 'form-control', name: 'utm_term', placeholder: 'identify the paid keywords: running+shoes', type: 'text'
            %span.input-group-addon
              %a{href: utm_help, target: 'utm_help'}
                %span.glyphicon.glyphicon-question-sign

      .form-group
        %label.col-sm-2.control-label{for: "utm_content"} Content
        .col-sm-10
          .input-group.input-group-sm
            = f.text_field :utm_content, class: 'form-control', name: 'utm_content', placeholder: 'use to differentiate ads: logolink, textlink', type: 'text'
            %span.input-group-addon
              %a{href: utm_help, target: 'utm_help'}
                %span.glyphicon.glyphicon-question-sign

      .form-group
        %label.col-sm-2.control-label{for: "utm_name"} Name
        .col-sm-10
          .input-group.input-group-sm
            = f.text_field :utm_name, class: 'form-control', name: 'utm_name', placeholder: 'use for keyword analysis: product, promo code, or slogan', type: 'text'
            %span.input-group-addon
              %a{href: utm_help, target: 'utm_help'}
                %span.glyphicon.glyphicon-question-sign

app/views/urls/edit.html.haml
= form_for @url, url: shortener_shortened_url_url(@url), html: {class: 'form-horizontal', role: 'form'} do |f|

  .panel.panel-default
    .panel-heading
      %h3.panel-title Edit #{@url.domain_name} URL:

    .panel-body
      = render partial: 'form', locals: {f: f}

    .panel-footer
      %btn-toolbar.pull-right
        %a.btn.btn-default.btn-larget{href: root_path} Cancel
        %button.btn.btn-primary.btn-large{type: "submit"} Update URL
      .clearfix
      

app/views/urls/index.html.haml
.jumbotron
  %h1 #{domain_name}
  %p
    Custom branded short URLs
    %span.pull-right
      %a.btn.btn-primary.btn-large{href: new_shortener_shortened_url_url} Create new short URL

.panel.panel-default
  .panel-heading
    %h5.pull-left Recent shortened URLs:
    .pull-right
      = form_tag shortener_shortened_urls_url, method: :get, class: "form-inline" do
        = text_field_tag :query, params[:query], placeholder: "Enter Short URL", class: "form-control", id: "short_url_query_input"
        = submit_tag "Search", class: "btn btn-default"
    .clearfix

  .panel-body
    %table.table.table-condensed.table_responsive
      %thead
        %tr
          %th
            short URL
          %th
            original URL
          %th
      %tbody
      - @urls.each do |url|
        %tr
          %td
            %a{href: "/#{url.unique_key}", target: url.unique_key}
              = condensed_url url
          %td
            %a{href: full_url(url), target: url.unique_key}
              = full_url(url).truncate(55)
          %td
            %button.btn.btn-primary.btn-xs.copy_button{:'data-clipboard-text' => valid_condensed_url(url)}
              copy
            %a.btn.btn-primary.btn-xs{href: shortener_shortened_url_path(url)}
              show
            %a.btn.btn-primary.btn-xs{href: edit_shortener_shortened_url_path(url)}
              edit

  .panel-footer
    = paginate @urls

:javascript
  var client = new ZeroClipboard( $(".copy_button") );
  client.on( "ready", function( readyEvent ) {
    // alert( "ZeroClipboard SWF is ready!" );
    client.on( "aftercopy", function( event ) {
      // `this` === `client`
      // `event.target` === the element that was clicked
      event.target.style.display = "none";
      alert("Copied text to clipboard: " + event.data["text/plain"] );
    } );
  } );
  

app/views/urls/new.html.haml
= form_for @url, url: shortener_shortened_urls_url, html: {class: 'form-horizontal', role: 'form'} do |f|

  .panel.panel-default
    .panel-heading
      %h3.panel-title New URL:

    .panel-body
      = render partial: 'form', locals: {f: f}

    .panel-footer
      %btn-toolbar.pull-right
        %a.btn.btn-default.btn-larget{href: root_path} Cancel
        %button.btn.btn-primary.btn-large{type: "submit"} Create URL
      .clearfix
      

app/views/urls/search.html.haml
.jumbotron
  %h1 #{domain_name}
  %p
    Custom branded short URLs
    %span.pull-right
      %a.btn.btn-primary.btn-large{href: new_shortener_shortened_url_url} Create new short URL

.panel.panel-default
  .panel-heading
    Recent shortened URLs:
    .text-right
      %form{action: '/search', method: 'get'}
        %input{:type => "text", name: 'q', placeholder: 'Search URL'}
        %input{:type => "submit", :value => "Search"}
  .panel-body
    %table.table.table-condensed.table_responsive
      %thead
        %tr
          %th
            short URL
          %th
            original URL
          %th
      %tbody
      - @urls.each do |url|
        %tr
          %td
            %a{href: "/#{url.unique_key}", target: url.unique_key}
              = condensed_url url
          %td
            %a{href: full_url(url), target: url.unique_key}
              = full_url(url).truncate(55)
          %td
            %button.btn.btn-primary.btn-xs.copy_button{:'data-clipboard-text' => valid_condensed_url(url)}
              copy
            %a.btn.btn-primary.btn-xs{href: shortener_shortened_url_path(url)}
              show
            %a.btn.btn-primary.btn-xs{href: edit_shortener_shortened_url_path(url)}
              edit

  .panel-footer
    = paginate @urls

:javascript
  var client = new ZeroClipboard( $(".copy_button") );
  client.on( "ready", function( readyEvent ) {
    // alert( "ZeroClipboard SWF is ready!" );
    client.on( "aftercopy", function( event ) {
      // `this` === `client`
      // `event.target` === the element that was clicked
      event.target.style.display = "none";
      alert("Copied text to clipboard: " + event.data["text/plain"] );
    } );
  } );

app/views/urls/show.html.haml
.span-12.jumbotron
  .well.well-lg
    %a.short_url{href: "/#{@url.unique_key}", target:@url.unique_key}
      = condensed_url @url
    %br
    #short_url.hidden
      = valid_condensed_url(@url)
    %br
    %button#clip_button.btn.btn-xs.btn-info.pull-right{"data-clipboard-target" => "short_url", "data-clipboard-text" => "Default clipboard text from attribute", :title => "Click me to copy to clipboard."}
      %b Copy To Clipboard...
    .clearfix
  %p
    Full URL:
    %a{href: full_url(@url), target:@url.unique_key}
      = full_url(@url).truncate(50)

  %btn-toolbar.pull-right
    %a.btn.btn-default.btn-larget{href: edit_shortener_shortened_url_path(@url)} Edit URL
    %a.btn.btn-primary.btn-larget{href: root_path} Done
  .clearfix

:javascript
  $(document).ready(function() {
    var clip = new ZeroClipboard($("#clip_button"))
  });